/**
 * Types for the shoppable-image manifest generated by
 * `scripts/generate-shoppable-manifest.mjs` from AESTHETIC pipeline results.
 * All coordinates are normalized 0–1 against the source image.
 */

export interface ShoppableProduct {
  name: string;
  brand: string | null;
  price: number | null;
  currency: string | null;
  /** Merchant product page — opened in a new tab. */
  url: string;
  /** Remote product image (merchant CDN). */
  image: string | null;
  /** Locally cached copy under /portfolio/shoppable/thumbs/, preferred over `image`. */
  localImage: string | null;
  merchant: string | null;
}

export interface ShoppableItem {
  boundId: string;
  label: string;
  category: string | null;
  /** Normalized center of the detected item — the limb's origin on the image. */
  anchor: { x: number; y: number };
  /** Normalized bounding box — traced on the image when the item's card is hovered. */
  box: { x: number; y: number; w: number; h: number };
  /** Ranked recommendations; the UI shows products[0]. Never empty in a valid manifest. */
  products: ShoppableProduct[];
}

export interface ShoppableEntry {
  shortCode: string;
  generatedAt: string;
  items: ShoppableItem[];
}

/** Keyed by `UniverseMedia.filename` (e.g. "c9c4….jpg"). */
export type ShoppableManifest = Record<string, ShoppableEntry>;
